// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import BuyTicketsController from "./buy_tickets_controller"
application.register("buy-tickets", BuyTicketsController)

import ConversationSubscriptionController from "./conversation_subscription_controller"
application.register("conversation-subscription", ConversationSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import RefreshMarkersController from "./refresh_markers_controller"
application.register("refresh-markers", RefreshMarkersController)

import SendMessageController from "./send_message_controller"
application.register("send-message", SendMessageController)
